#!/bin/sh
#
# Generated at https://tools.adcirc.live on #
#-------------------------------------------------------------------
# config.sh: This file is read at the beginning of the execution of the ASGS to
# set up the runs  that follow. It is reread at the beginning of every cycle,
# every time it polls the datasource for a new advisory. This gives the user
# the opportunity to edit this file mid-storm to change config parameters
# (e.g., the name of the queue to submit to, the addresses on the mailing list,
# etc)
#-------------------------------------------------------------------
#
# Copyright(C) 2024 Jason Fleming <jason.fleming@adcirc.live>
# Copyright(C) 2024 Brett Estrade <brett.estrade@adcirc.live>
#
# This file is part of the ADCIRC Surge Guidance System (ASGS) and has been
# generated by ADCIRC Live (C) - https://tools.adcirc.live
#
# The ASGS is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# ASGS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# It is available for free at https://github.com/StormSurgeLive/asgs
#
# See the results available, particularly for tropical cyclones at LSU's CERA,
#   COASTAL EMERGENCY RISKS ASSESSMENT
#     ~ Storm Surge Guidance for Emergency Management and Real-Time Decisions ~
#
#   https://cera.coastalrisk.live
#
# You should have received a copy of the GNU General Public License along with
# the ASGS.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------

# Fundamental General Identifying Info

# "name" of this ASGS process
INSTANCENAME=HSOFS_al042024_ls6_be
ASGSADMIN=asgsnotify@memenesia.net

# HPC/Queue System Settings
# used on HPC's to specify allocation account
ACCOUNT=ADCIRC
# used for priority access at TACC
QOS=vipPJ_P3000
# Input Files and Templates 

GRIDNAME=HSOFS
source $SCRIPTDIR/config/mesh_defaults.sh

# Start State Information

# Note: Initial state (overridden by STATEFILE after ASGS gets going since it's then a "hotstart")
HOTORCOLD=hotstart
HINDCASTLENGTH=30  # length of initial hindcast, from cold (days)
COLDSTARTDATE=$(get-coldstart-date)  # already computes based on HINDCASTLENGTH (default is 30 days before TODAY)
LASTSUBDIR=https://fortytwo.cct.lsu.edu/thredds/fileServer/2024/GFS/2024080212/HSOFS/qbc.loni.org/HSOFS_gfs_qbc_sn/gfsforecast/       # used when HOTORCOLD=hotstart

# Physical Forcing (defaults set in config/forcing_defaults.sh)

TIDEFAC=on                        # tide factor recalc
BACKGROUNDMET=off            # download/ meteorological forcing from an upstream source
   FORECASTCYCLE=         # used when BACKGROUNDMET is turned on ("on", "NAM", "GFS", etc)
TROPICALCYCLONE=on        # tropical cyclone forcing (mutually exclusive with BACKGROUNDMET in most cases)
   STORM=04                         # storm number, e.g. 05=ernesto in 2006
   YEAR=2024                           # year of the storm
   BASIN=al                         # ocean basin, e.g., AL (Atlantic), EP (East Pacific)
WAVES=on                            # wave forcing via built-in SWAN coupling (adcswan/padcswan)
   REINITIALIZESWAN=off   # used to bounce the wave solution (only used when WAVES=on)
VARFLUX=off                        # variable river flux forcing
CYCLETIMELIMIT=99:00:00          # max time, usually just 99:00:00

# Computational Resources (related defaults set in platforms.sh)

PPN=128                   # platform specific, processors-per-node
NCPU=959                 # number of compute CPUs for all simulations, should be a set in consideration of PPN
NUMWRITERS=1     # usually just 1, total CPUs for the run is NCPU+NUMWRITERS
QUEUESYSTEM=SLURM   # platform specific, e.g., SLURM
NCPUCAPACITY=9999 # max number of total CPUs to use

# JSON Logging
enablePostStatus=yes
enableStatusNotify=no
statusNotify="asgsnotify@memenesia.net"

# Post processing and publication
EMAILNOTIFY=yes
INTENDEDAUDIENCE=general              # Settings for CERA to help determine where to post results; "general" | "developers-only"
OPENDAPPOST=opendap_post2.sh                        # usually, "opendap_post2.sh"; for posting to OpenDAP/THREDDS servers via ssh
POSTPROCESS=(  $OPENDAPPOST )  # scripts to run during the POSTPROCESS ASGS hook
# email list receiving alerts via bin/asgs-sendmail
OPENDAPNOTIFY="coastalrisk.live@outlook.com,pub.coastalrisk.live@outlook.com,asgs.cera.lsu@coastalrisk.live,asgs.cera.pub.lsu@coastalrisk.live,asgsnotify@memenesia.net,jasongfleming@gmail.com,cdelcastillo21@gmail.com"
NOTIFY_SCRIPT=cera_notify.sh                    # notification used ... 
TDS=( lsu_tds )                                    # servers receiving results via ssh

#
# Scenario package
#

# Used for Hindcast Only configurations
#HINDCASTONCE_AND_EXIT=
#PERCENT=default
SCENARIOPACKAGESIZE=2 
case $si in
 -2)
   ENSTORM=hindcast            # initial ramp up during a coldstart
   OPENDAPNOTIFY="coastalrisk.live@outlook.com,pub.coastalrisk.live@outlook.com,asgs.cera.lsu@coastalrisk.live,asgs.cera.pub.lsu@coastalrisk.live,asgsnotify@memenesia.net,jasongfleming@gmail.com,cdelcastillo21@gmail.com"
   ;;
-1)
   ENSTORM=nowcast             # do nothing ... this is "catch up", not a forecast 
   OPENDAPNOTIFY="null"
   ;;
0)
   ENSTORM=nhcConsensus
   PERCENT=0
   OPENDAPNOTIFY="coastalrisk.live@outlook.com,pub.coastalrisk.live@outlook.com,asgs.cera.lsu@coastalrisk.live,asgs.cera.pub.lsu@coastalrisk.live,asgsnotify@memenesia.net,jasongfleming@gmail.com,cdelcastillo21@gmail.com"
   source $SCRIPTDIR/config/io_defaults.sh
   ;;
1)
   ENSTORM=nhcConsensusWind10m
   PERCENT=0
   OPENDAPNOTIFY="coastalrisk.live@outlook.com,pub.coastalrisk.live@outlook.com,asgs.cera.lsu@coastalrisk.live,asgs.cera.pub.lsu@coastalrisk.live,asgsnotify@memenesia.net,jasongfleming@gmail.com,cdelcastillo21@gmail.com"
   source $SCRIPTDIR/config/io_defaults.sh
   ;;
*)
   echo "CONFIGRATION ERROR: Unknown scenario number: '$si'."
   ;;
esac

source $SCRIPTDIR/config/io_defaults.sh # sets met-only mode based on "Wind10m" suffix

PREPPEDARCHIVE=prepped_${GRIDNAME}_${INSTANCENAME}_${NCPU}.tar.gz
HINDCASTARCHIVE=prepped_${GRIDNAME}_hc_${INSTANCENAME}_${NCPU}.tar.gz
